spring:
  application:
    name: employee-service

  devtools:
    add-properties: true

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/micro_employee_db
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081